### ISSUE TITLE
Skip building demos and IT's modules when not needed

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-flow-components#10]
In the case of `-DskipTests`  and `-DskipITs` or other cases we can skip running `npm install` etc

**Comment by ZheSun88** [comment]
existing profile can be used to skip IT tests. `-Drelease`
added one more profile to the project. 
demo build can be skiped by add `-DnoDemo` to maven command line
```java
<profile>
			<id>build-demo</id>
			<activation>
				<property>
					<name>!noDemo</name>
				</property>
			</activation>
			<modules>
				<module>vaadin-XXXXX-flow-demo</module>
			</modules>
		</profile>
```
