### ISSUE TITLE
Archive 36 repos 

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-flow-components#166]
### 6 Oct 2020
 - [x] Technical release 14.4.0 
 - [x] V14 release notes in draft mode
 - [x] message to [#engineering-team](https://vaadin.slack.com/archives/G9EU978QM) commit rules for the new monorepo
 
### 7 Oct 2020
 - [x] Publish V14 release notes (~9:00am)
 - [x] Announce V14.0.0 in announcements (~9:00am)
 - [x] Switch to monorepo (~8:00am)
   - [x] message to [#engineering-team](https://vaadin.slack.com/archives/G9EU978QM) not to work with any flow-component
   - [x] run [scripts/transferTicket.js](https://github.com/vaadin/vaadin-flow-components/blob/transfer-ticket/scripts/transferTicket.js) (takes ?? )
     - [x] check that all tickets were migrated (it should be done before 8:00pm) 
     - [x] check that all labels are in place (8:00pm) the script above should create them
   - [x] run [scripts/mergeAllReposWithHistory.sh](https://github.com/vaadin/vaadin-flow-components/blob/merge-repos/scripts/mergeAllReposWithHistory.sh) (takes 30') 8:15pm
   - [x] delete [Bender build](https://bender.vaadin.com/viewType.html?buildTypeId=VaadinFlowComponents_UpdateFilesInBranchFromOriginalRepo) that synchronises master and other branches
   - [x] archive 36 repos. Per each repo we have to perform the next steps (starting at 8:45)
      - Modify README file to include the next text [1]
      - Modify all active PR's to include the text [2]
      - archive the repo 
  - [x] message to [#engineering-team](https://vaadin.slack.com/archives/G9EU978QM) they can checkout the monorepo and start working with it (~11:00 am)
  - [x] ask Artem to add vaadin-flow-components to the dashboard (~11:30)
- [x] run [scripts/mergeAllReposWithHistory.sh](https://github.com/vaadin/vaadin-flow-components/blob/merge-repos/scripts/mergeAllReposWithHistory.sh) in 14.4
- [x] create 14.5 branch in platform
- [x] create 14.5 branch in vaadin-flow-components
  - based on 14.4 merged
- [x] run [scripts/mergeAllReposWithHistory.sh](https://github.com/vaadin/vaadin-flow-components/blob/merge-repos/scripts/mergeAllReposWithHistory.sh) in 17.0
- [x] ask PR authors in the monorepo to rebase their branches

  ## List of repos to archive
 - [x] [vaadin-accordion-flow](https://github.com/vaadin/vaadin-accordion-flow)|[PRs](https://github.com/vaadin/vaadin-accordion-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-accordion-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-accordion-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-accordion-flow/settings/#danger-zone)
 - [x] [vaadin-avatar-flow](https://github.com/vaadin/vaadin-avatar-flow)|[PRs](https://github.com/vaadin/vaadin-avatar-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-avatar-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-avatar-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-avatar-flow/settings/#danger-zone)
 - [x] [vaadin-app-layout-flow](https://github.com/vaadin/vaadin-app-layout-flow)|[PRs](https://github.com/vaadin/vaadin-app-layout-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-app-layout-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-app-layout-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-app-layout-flow/settings/#danger-zone)
 - [x] [vaadin-button-flow](https://github.com/vaadin/vaadin-button-flow)|[PRs](https://github.com/vaadin/vaadin-button-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-button-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-button-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-button-flow/settings/#danger-zone)
 - [x] [vaadin-checkbox-flow](https://github.com/vaadin/vaadin-checkbox-flow)|[PRs](https://github.com/vaadin/vaadin-checkbox-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-checkbox-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-checkbox-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-checkbox-flow/settings/#danger-zone)
 - [x] [vaadin-combo-box-flow](https://github.com/vaadin/vaadin-combo-box-flow)|[PRs](https://github.com/vaadin/vaadin-combo-box-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-combo-box-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-combo-box-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-combo-box-flow/settings/#danger-zone)
 - [x] [vaadin-context-menu-flow](https://github.com/vaadin/vaadin-context-menu-flow)|[PRs](https://github.com/vaadin/vaadin-context-menu-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-context-menu-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-context-menu-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-context-menu-flow/settings/#danger-zone)
 - [x] [vaadin-custom-field-flow](https://github.com/vaadin/vaadin-custom-field-flow)|[PRs](https://github.com/vaadin/vaadin-custom-field-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-custom-field-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-custom-field-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-custom-field-flow/settings/#danger-zone)
 - [x] [vaadin-date-picker-flow](https://github.com/vaadin/vaadin-date-picker-flow)|[PRs](https://github.com/vaadin/vaadin-date-picker-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-date-picker-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-date-picker-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-date-picker-flow/settings/#danger-zone)
 - [x] [vaadin-date-time-picker-flow](https://github.com/vaadin/vaadin-date-time-picker-flow)|[PRs](https://github.com/vaadin/vaadin-date-time-picker-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-date-time-picker-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-date-time-picker-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-date-time-picker-flow/settings/#danger-zone)
 - [x] [vaadin-details-flow](https://github.com/vaadin/vaadin-details-flow)|[PRs](https://github.com/vaadin/vaadin-details-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-details-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-details-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-details-flow/settings/#danger-zone)
 - [x] [vaadin-dialog-flow](https://github.com/vaadin/vaadin-dialog-flow)|[PRs](https://github.com/vaadin/vaadin-dialog-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-dialog-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-dialog-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-dialog-flow/settings/#danger-zone)
 - [x] [vaadin-form-layout-flow](https://github.com/vaadin/vaadin-form-layout-flow)|[PRs](https://github.com/vaadin/vaadin-form-layout-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-form-layout-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-form-layout-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-form-layout-flow/settings/#danger-zone)
 - [x] [vaadin-grid-flow](https://github.com/vaadin/vaadin-grid-flow)|[PRs](https://github.com/vaadin/vaadin-grid-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-grid-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-grid-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-grid-flow/settings/#danger-zone)
 - [x] [vaadin-icons-flow](https://github.com/vaadin/vaadin-icons-flow)|[PRs](https://github.com/vaadin/vaadin-icons-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-icons-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-icons-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-icons-flow/settings/#danger-zone)
 - [x] [vaadin-iron-list-flow](https://github.com/vaadin/vaadin-iron-list-flow)|[PRs](https://github.com/vaadin/vaadin-iron-list-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-iron-list-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-iron-list-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-iron-list-flow/settings/#danger-zone)
 - [x] [vaadin-list-box-flow](https://github.com/vaadin/vaadin-list-box-flow)|[PRs](https://github.com/vaadin/vaadin-list-box-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-list-box-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-list-box-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-list-box-flow/settings/#danger-zone)
 - [x] [vaadin-login-flow](https://github.com/vaadin/vaadin-login-flow)|[PRs](https://github.com/vaadin/vaadin-login-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-login-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-login-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-login-flow/settings/#danger-zone)
 - [x] [vaadin-menu-bar-flow](https://github.com/vaadin/vaadin-menu-bar-flow)|[PRs](https://github.com/vaadin/vaadin-menu-bar-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-menu-bar-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-menu-bar-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-menu-bar-flow/settings/#danger-zone)
 - [x] [vaadin-notification-flow](https://github.com/vaadin/vaadin-notification-flow)|[PRs](https://github.com/vaadin/vaadin-notification-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-notification-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-notification-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-notification-flow/settings/#danger-zone)
 - [x] [vaadin-ordered-layout-flow](https://github.com/vaadin/vaadin-ordered-layout-flow)|[PRs](https://github.com/vaadin/vaadin-ordered-layout-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-ordered-layout-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-ordered-layout-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-ordered-layout-flow/settings/#danger-zone)
 - [x] [vaadin-progress-bar-flow](https://github.com/vaadin/vaadin-progress-bar-flow)|[PRs](https://github.com/vaadin/vaadin-progress-bar-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-progress-bar-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-progress-bar-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-progress-bar-flow/settings/#danger-zone)
 - [x] [vaadin-radio-button-flow](https://github.com/vaadin/vaadin-radio-button-flow)|[PRs](https://github.com/vaadin/vaadin-radio-button-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-radio-button-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-radio-button-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-radio-button-flow/settings/#danger-zone)
 - [x] [vaadin-select-flow](https://github.com/vaadin/vaadin-select-flow)|[PRs](https://github.com/vaadin/vaadin-select-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-select-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-select-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-select-flow/settings/#danger-zone)
 - [x] [vaadin-split-layout-flow](https://github.com/vaadin/vaadin-split-layout-flow)|[PRs](https://github.com/vaadin/vaadin-split-layout-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-split-layout-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-split-layout-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-split-layout-flow/settings/#danger-zone)
 - [x] [vaadin-tabs-flow](https://github.com/vaadin/vaadin-tabs-flow)|[PRs](https://github.com/vaadin/vaadin-tabs-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-tabs-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-tabs-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-tabs-flow/settings/#danger-zone)
 - [x] [vaadin-text-field-flow](https://github.com/vaadin/vaadin-text-field-flow)|[PRs](https://github.com/vaadin/vaadin-text-field-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-text-field-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-text-field-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-text-field-flow/settings/#danger-zone)
 - [x] [vaadin-time-picker-flow](https://github.com/vaadin/vaadin-time-picker-flow)|[PRs](https://github.com/vaadin/vaadin-time-picker-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-time-picker-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-time-picker-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-time-picker-flow/settings/#danger-zone)
 - [x] [vaadin-upload-flow](https://github.com/vaadin/vaadin-upload-flow)|[PRs](https://github.com/vaadin/vaadin-upload-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-upload-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-upload-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-upload-flow/settings/#danger-zone)
 - [x] [vaadin-board-flow](https://github.com/vaadin/vaadin-board-flow)|[PRs](https://github.com/vaadin/vaadin-board-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-board-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-board-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-board-flow/settings/#danger-zone)
 - [x] [vaadin-charts-flow](https://github.com/vaadin/vaadin-charts-flow)|[PRs](https://github.com/vaadin/vaadin-charts-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-charts-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-charts-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-charts-flow/settings/#danger-zone)
 - [x] [vaadin-confirm-dialog-flow](https://github.com/vaadin/vaadin-confirm-dialog-flow)|[PRs](https://github.com/vaadin/vaadin-confirm-dialog-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-confirm-dialog-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-confirm-dialog-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-confirm-dialog-flow/settings/#danger-zone)
 - [x] [vaadin-cookie-consent-flow](https://github.com/vaadin/vaadin-cookie-consent-flow)|[PRs](https://github.com/vaadin/vaadin-cookie-consent-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-cookie-consent-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-cookie-consent-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-cookie-consent-flow/settings/#danger-zone)
 - [x] [vaadin-crud-flow](https://github.com/vaadin/vaadin-crud-flow)|[PRs](https://github.com/vaadin/vaadin-crud-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-crud-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-crud-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-crud-flow/settings/#danger-zone)
 - [x] [vaadin-grid-pro-flow](https://github.com/vaadin/vaadin-grid-pro-flow)|[PRs](https://github.com/vaadin/vaadin-grid-pro-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-grid-pro-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-grid-pro-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-grid-pro-flow/settings/#danger-zone)
 - [x] [vaadin-rich-text-editor-flow](https://github.com/vaadin/vaadin-rich-text-editor-flow)|[PRs](https://github.com/vaadin/vaadin-rich-text-editor-flow/pulls?q=is%3Apr+is%3Aclosed)|[Master](https://github.com/vaadin/vaadin-rich-text-editor-flow/settings/branches)|[README](https://github.com/vaadin/vaadin-rich-text-editor-flow/edit/master/README.md)|[Archive](https://github.com/vaadin/vaadin-rich-text-editor-flow/settings/#danger-zone)

[1] **Text for deprecated repos**

 ⚠️ **This repository is deprecated**
- Sources for this flow component can be found at https://github.com/vaadin/vaadin-flow-components
- Tickets has been moved to the web component repository https://github.com/vaadin/<vaadin-component>

[2] **Text for non-migrated PRs**

This PR has been closed without merging because sources of this component has been moved to
the  https://github.com/vaadin/vaadin-flow-components repository.

Please if you still consider that this change is still valid, open a PR to that repository in order to
continue the discussion and eventually apply it.
        
Thank you and sorry for the inconvenience.

**Comment by ZheSun88** [comment]
@jhult thanks Jonathan, we are going to fix it soon.

**Comment by manolo** [comment]
@jhult The template used had wrong links, we have fixed it and updated all links, thanks
