### ISSUE TITLE
Re-enable ignored flaky tests for ContextMenu

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-flow-components#181]
During migration to NPM, we could see that there are two tests that fail randomly.
Feature works when reproducing test steps manually in both npm and bower mode
They are marked as ignored to speed up component migration to flow 2.0
- `SubMenuIT.openAndCloseSubMenu_addSubSubMenu_contentUpdatedAndFunctional`
- `SubMenuIT.openAndCloseSubMenu_addContent_contentUpdatedAndFunctional`

**Comment by web-padawan** [comment]
These tests were re-enabled by #349.
