### ISSUE TITLE
Re-enable ignored flaky tests for RichTextEditor

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-flow-components#182]
Two tests are failing for component migrated to NPM :
`BasicUseIT::setValueCorrectly` and `BasicUseIT::richTextEditorInATemplate_settingAndGettingValueCorrectly`.

They pass locally (at least for Chrome).

Investigate the reason and enable them back.

**Comment by web-padawan** [comment]
These tests were re-enabled by #349.
