### ISSUE TITLE
Remove pinned npm version from main view in IT module

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/vaadin-flow-components#184]
There was an issue with two versions of `vaadin-text-field` in the IT module and in vaadin/vaadin-grid-pro-flow#104 and vaadin/vaadin-grid-pro-flow#105, as a workaround, `vaadin-select` was pinned in MainView class.

Probably can be solved when `vaadin-text-field-flow` is bumped to a new minor.

**Comment by web-padawan** [comment]
Here is the code on master, hopefully it can be safely removed for V18.

https://github.com/vaadin/vaadin-flow-components/blob/342baa535db3a1206ebd96580a0341abea50d282/vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/examples/MainView.java#L23-L24

**Comment by web-padawan** [comment]
The line linked in the above comment https://github.com/vaadin/vaadin-flow-components/issues/184#issuecomment-704337561 was removed by c20d6ad80c64fdd6b2c64df071ab2cc78f8805bd. Closing.
