### ISSUE TITLE
All components should have subproject structure aligned

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-flow-components#19]
Most projects name the testbench library as `vaadin-nnn-flow-testbench` but there are a bunch of then that are not aligned

```
vaadin-app-layout-flow-parent/vaadin-app-layout-testbench
vaadin-board-flow-parent/vaadin-board-testbench
vaadin-charts-flow-parent/testbench
vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-testbench
vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-testbench
```
For the case of `vaadin-charts-flow` the problem is worst since all submodules are unaligned 

```
 addon  -> vaadin-charts-flow
 documentation 
 examples -> vaadin-charts-flow-demo
 integration-test -> vaadin-charts-flow-integration-tests
 testbench -> vaadin-charts-flow-testbench
```

Related to: https://github.com/vaadin/vaadin-charts-flow/issues/377

**Comment by ZheSun88** [comment]
Besides the above:

`vaadin-accordion-flow-parent/vaadin-accordion-testbench/`
`vaadin-grid-pro-flow-parent/vaadin-grid-pro-testbench/`
`vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-testbench/`
`crud` `custom-field`
it looks all pro components have used `vaadin-component-testbench` format

**Comment by manolo** [comment]
Done
