### ISSUE TITLE
Bender: list tests that were run/failed in the Release build

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-flow-components#206]
In 'Pull Request Validation' (teamcity), list of builds report the number of tests run/failed
![image.png](https://images.zenhubusercontent.com/55e2adbd4f7a08fbb7f49916/c594f2a9-9e5c-4a62-8d21-7b248d9ecdc8)

In 'Snapshot - Flow Components' (bender), the list just report 'Success' 
![image.png](https://images.zenhubusercontent.com/55e2adbd4f7a08fbb7f49916/441889f5-378d-4c54-b964-16f843b17afc)

The problem is that tests are run in an intermediate step

**Comment by ZheSun88** [comment]
This ticket is misleading. 

As not all the PR validation build report the number of tests/failures
![image](https://user-images.githubusercontent.com/31067185/95724596-3ab12580-0c7f-11eb-8b9c-63c480eef9ff.png)
