### ISSUE TITLE
Unify automation Scripts for NpmPakage, Webjars, Platform 

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-flow-components#233]
Let's run all script in a single build because
 - NpmPackage and Webjars can go in the same PR to flow-components
 - Platform script needs that NpmPackage were previously updated

**Comment by ZheSun88** [comment]
Combined the NpmPackage and webjar build into the same one:  https://bender.vaadin.com/viewType.html?buildTypeId=VaadinFlowComponents_FlowComponentsUpdateNpmPackagesWebjarsVersions

**Comment by ZheSun88** [comment]
the `updateplatform.sh` takes the branch info directly from the build, which makes it impossible to work with PRs (as those branch name is not formulated. ) 

make a PR to allow passing branch info to the script. #254 

after that, we can modify [this build](https://bender.vaadin.com/admin/editRunType.html?id=buildType:VaadinFlowComponents_FlowComponentsUpdateNpmPackagesWebjarsVersions&runnerId=RUNNER_768&cameFromUrl=%2Fadmin%2FeditBuildRunners.html%3Fid%3DbuildType%253AVaadinFlowComponents_FlowComponentsUpdateNpmPackagesWebjarsVersions%26init%3D1&cameFromTitle=) to pass the %env.basebranch%
