### ISSUE TITLE
Grid demo of item details includes unused event handler

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/vaadin-flow-components#235]
Grid demo of item details (https://vaadin.com/components/vaadin-grid/java-examples/item-details) includes an unused event handler. 

```
.withEventHandler("handleClick", person -> {
            grid.getDataProvider().refreshItem(person);
        }
```

**Comment by web-padawan** [comment]
Fixed by https://github.com/vaadin/vaadin-flow-components/pull/236 which was merged to `14.5` branch and the issue was left open because of that. Closing.
