### ISSUE TITLE
Identical Issue #8891, Vaadin 17.0.8

### ISSUE THREAD

**Issue by aelkman** [vaadin/vaadin-flow-components#344]
This is a cloned bug found here https://github.com/vaadin/flow/issues/8891
also in Vaadin 17, is there a planned fix in Vaadin 17 coming soon? 

Build has been updated to 17.0.8 and problem persists when Grid reads a null nested property from my JPARepository class. Can provide more code if needed but again this appears to be an identical issue.

**Comment by DiegoCardoso** [comment]
Hello @aelkman,

The fix for this came as a new feature, so the developer can decide whether they want an error to be thrown (default) or not. For that reason, it cannot be ported to Vaadin 17, so this feature will come for Vaadin 18.
