### ISSUE TITLE
Unexpected behavior when using HorizontalLayout with justify content

### ISSUE THREAD

**Issue by rolandoisidoro** [vaadin/vaadin-flow-components#364]
When using `HorizontalLayout` with justify content, `FlexComponent.JustifyContentMode`s `AROUND`, `BETWEEN` and `EVENLY` are not behaving as expected, according to [MDN web docs `justify-content` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content) examples.

From the HorizontalLayout with justify content section of the [Ordered Layout Java Examples at Vaadin's official docs](https://vaadin.com/components/vaadin-ordered-layout/java-examples/horizontallayout), they all have excessive space to the left:

#### BETWEEN
![image](https://user-images.githubusercontent.com/1101532/98096180-51fcc080-1e83-11eb-8cd3-c11688ca57bc.png)

#### AROUND
![image](https://user-images.githubusercontent.com/1101532/98096309-81133200-1e83-11eb-88ae-894166988347.png)

#### EVENLY
![image](https://user-images.githubusercontent.com/1101532/98096360-938d6b80-1e83-11eb-9969-3f4caaaf1750.png)

**Comment by web-padawan** [comment]
Thanks for the issue. Closing in favor of https://github.com/vaadin/vaadin-ordered-layout/issues/66 where it is discussed.
