### ISSUE TITLE
Cannot set a value for a lazy loaded ComboBox

### ISSUE THREAD

**Issue by ziza** [vaadin/vaadin-flow-components#391]
Vaadin 18.0.0.rc1
Vaadin 18.0.0.rc2

`ComboBox<Person> comboBox = new ComboBox<>();`
`ComboBoxLazyDataView<Person> dataView = comboBox.setItems(query -> {`
`	return service.fetch(query).stream();`
`});`
`Person person = service.findById(1);`
`comboBox.setValue(person);`

`comboBox.setValue` throws:
"java.lang.IllegalStateException: Cannot set a value for a ComboBox without items. Use setItems to populate items into the ComboBox before setting a value.
	at com.vaadin.flow.component.combobox.ComboBox.setValue(ComboBox.java:371)"

**Comment by mstahv** [comment]
@tomivirkki @mshabarov @pleku @rolfsmeds 
Just noticed this issue, looks like we haven't been following this new repository for new issues! This is a critical issue that needs to get fixed asap. There seems to be [some validation](https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L367-L376), that should only be done for in-memory data sets.

Let's get this fixed ASAP.
