### ISSUE TITLE
Cannot sort a Grid that is initially hidden

### ISSUE THREAD

**Issue by petrixh** [vaadin/vaadin-flow-components#427]
If a Grid is hidden inside a Detail or an Accordion, apparently it is not possible to initialise the Grid with a sort order if the Grid in question is initially hidden. 

Minimal reproducible example for a hello world Vaadin app:

`    
    // Tested with: 
    // Vaadin 14.3.8  
   // Vaadin 14.3.9
   // Vaadin 14.4.2
    
    @Route("gridbug")
    public class GridBug extends VerticalLayout {

    public static class ItemObject{
        private String value;

        public ItemObject(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }
    }

    //Note same happens with Accordion...
    public GridBug() {

        Details detail1 = new Details("If visible, it works", createGrid());
        detail1.setOpened(true);
        add(detail1);

        // A hidden grid with Sort will not show any rows once the detail or
        // Accordion is expanded to show the grid
        Details detail2 = new Details("If hidden, not so much", createGrid());
        detail2.setOpened(false);
        add(detail2);

        // Just to make the view more visible... breaks just the same without this...
        detail1.getElement().getStyle().set("width", "100%");
        detail2.getElement().getStyle().set("width", "100%");
    }

    private Grid<ItemObject> createGrid() {
        ArrayList<ItemObject> items = new ArrayList<>();

        for(int i=0; i<100; i++){
            items.add(new ItemObject("Item: " + i));
        }

        Grid<ItemObject> grid = new Grid<>(ItemObject.class, false);
        grid.setWidthFull();
        grid.setItems(items);
        grid.setMultiSort(true);

        grid.addColumn(ItemObject::getValue).setHeader("Col 1").setKey("value").setSortable(true);
        grid.addColumn(ItemObject::getValue).setHeader("Col 2").setKey("value2").setSortable(true);
        grid.addColumn(ItemObject::getValue).setHeader("Col 3").setKey("value3").setSortable(true);
        grid.addColumn(ItemObject::getValue).setHeader("Col 4").setKey("value4").setSortable(true);
        grid.addColumn(ItemObject::getValue).setHeader("Col 5").setKey("value5").setSortable(true);

        //Why does this line break the entire grid if the grid is not visible intially?!?
        grid.sort(GridSortOrder.asc(grid.getColumnByKey("value")).build());

        return grid;
    }
}` 

No errors show up either in the client- or server-side console. 

Browser: Latest Chrome 87 on Windows 10 and OS X, also Chromium Edge on Win10, but seems to be browser independent... 
Vaadin version: at least 14.3.8 -> 
Expected: A "hidden" Grid should be able to have an initial sort order.

**Comment by yuriy-fix** [comment]
Fix was reverted as it was causing regressions: https://github.com/vaadin/vaadin-flow-components/pull/551. Better solution need to be found.
