### ISSUE TITLE
Potential path traversal in com.vaadin.flow.component.upload.receivers.AbstractFileBuffer#AbstractFileBuffer()

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/vaadin-flow-components#447]
Constructor of `AbstractFileBuffer` creates a factory which makes a prefix for a temp file from a supplied string, that is coming straight from Request without any sanitization:

https://github.com/vaadin/vaadin-flow-components/blob/36981ab480d6e41cfd770f8768eaad2be048c375/vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/AbstractFileBuffer.java#L38-L44

As a result, temp file might get created in an unexpected place and with unexpected name.

**Comment by tulioag** [comment]
Internally,  paths are removed in `File.generateFile` (OpenJDK 11)
``` java
 prefix = (new File(prefix)).getName();
```
So this code 
```java
        File file = File.createTempFile(".././../a.t",null);
        System.out.println(file.getAbsolutePath());
```
prints `/tmp/a.t753526972481436270.tmp`.


@fluorumlabs , can you provide a string that would cause an issue? Which characters need to be escaped?

**Comment by fluorumlabs** [comment]
You are correct :)
