### ISSUE TITLE
Vaadin text area is unusable in firefox with large amounts of text. 

### ISSUE THREAD

**Issue by jsalts** [vaadin/vaadin-flow-components#452]
### Description of the bug / feature
Vaadin text area is broken in firefox when using backspace with large amounts of text. 

### Minimal reproducible example
1. Download vaadin my-starter-project
2. On the home view, add a textarea to the content panel. 
3. Perform the steps in this screencast. 
   a. Populate the text area with a large amount of text. 
   b. Scroll near the bottom. 
   c. Attempt to delete a character using the backspace key. After hitting the backspace key once, the screen jumps up, making further text entry extremely difficult. The issue is specific to firefox and the vaadin text area component. The html textarea tag is not affected, so it is likely to do with the vaadin styling attached to the text area.

https://www.screencast.com/t/KMMoS3JQbT

### Expected behavior
The browser should not jump around. 
### Actual behavior
The browser jumps, making typing impossible. 

### Versions:
    - Vaadin / Flow version: 14.4.1
    - Java version: Java 11
    - OS version: 10.15.7 osx. 
    - Browser version (if applicable): firefox 83 (works in chrome)

**Comment by web-padawan** [comment]
Possibly related: https://github.com/angular/material/issues/3070

**Comment by jsalts** [comment]
FWIW setting max-height does help, but only if the max-height is less than 350px. In our use case we prefer to have larger sizes for the text area.

**Comment by jsalts** [comment]
Issue hasn't been fixed and now happens in chrome. The scroll happens when this line is executed. 

`    this.value = e.target.value;
`

**Comment by tomivirkki** [comment]
Hi @jsalts, if there's a regression or a related bug, please open a new GH issue (and reference this one) so it gets triaged properly. This one has already been closed/archived.
