### ISSUE TITLE
Open Notifications steal other components

### ISSUE THREAD

**Issue by joschkakissel** [vaadin/vaadin-flow-components#460]
Hello,

in our usecase we want to be able to show more than the standard notification provided by Notification.show() and on top multiple notifications might be displayed at the same time.

### Description of the bug / feature
So we create Notification objects, fill them with all the content and then use the open() function.
that works just fine till here. 

If now the user presses F5 to refresh the browser page, some notifications loose their original content, and instead "grab" something off the page. 

### Steps to reproduce
- load the page
- press the button quickly in succession until around 10 notifications are displayed
- press F5 to reload before the notifications disappear
--> after reload some notifications will have different content

### Minimal reproducible example

Here is an example project to showcase the behaviour
[VaadinNotificationBug.zip](https://github.com/vaadin/vaadin-flow-components/files/5603439/VaadinNotificationBug.zip)

`
@SpringBootApplication
@Route("")
@PWA(name = "Project Base for Vaadin Flow with Spring", shortName = "Project Base")
@UIScope
@PreserveOnRefresh
public class VaadinNotificationBugApplication extends VerticalLayout {

    public static void main(String[] args) {
        SpringApplication.run(VaadinNotificationBugApplication.class, args);
    }

    public VaadinNotificationBugApplication() {
        // Have a clickable button
        add(new Button("Push Me!!",
                click -> notify(new Label("MESSAGE"))));

        // Display the greeting
        add(new Label("Hello World!"));
        for (int i = 0; i < 10; i++) {
            add(new Label("label number " + i));
        }
    }

    public static void notify(Label label) {
        Notification n = new Notification();
        n.setDuration(2000);
        n.setPosition(Notification.Position.MIDDLE);
        n.add(label);
        n.open();
    }
}`

### Expected behavior
After pressing F5 the visible Notifications should be reloaded in the same state as before 

### Actual behavior
After pressing F5 the visible Notifications should are sometimes reloaded holding components from other places.

here an example:
Before:
![Before F5](https://user-images.githubusercontent.com/75081424/100359891-78cc9380-2ff8-11eb-91d7-c2ee2634398b.png)
and After:
![After F5](https://user-images.githubusercontent.com/75081424/100359942-8b46cd00-2ff8-11eb-967b-b9be880ad793.png)

### Versions:
    - Vaadin / Flow version: 14.4.2
    - Java version: 11 
    - OS version: Problably Any, but tested under Windows 10, Ubuntu and Debian, current versions respectivly
    - Browser version (if applicable): tested on Chrome, Firefox and Edge

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/vaadin-notification/issues/114
