### ISSUE TITLE
Tests using GridElement do not work with Vaadin 17.0.1 when using <vaadin-grid> and not Grid.java #1115

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-flow-components#470]
This is the same issue as https://github.com/vaadin/vaadin-grid-flow/issues/1115

It is marked fixed but is not

**Comment by Artur-** [comment]
You can see from https://github.com/vaadin/vaadin-grid-flow/pull/1116/files#diff-c4c6eb2e23e3729eafc436454a2ebf3dc8393fc8e279445a3557cd87d222a6ddR41 that the check now does
```
return false || undefined
```
which becomes `undefined` and `return (Boolean) executeScript("return undefined");` throws an exception.

It would have been good to test the fix, even manually

**Comment by TatuLund** [comment]
Is this different case than https://github.com/vaadin/vaadin-flow-components/issues/476 ?
