### ISSUE TITLE
Accordion and Details are missing Java API for setting class name

### ISSUE THREAD

**Issue by juuso-vaadin** [vaadin/vaadin-flow-components#564]
Accordion, AccordionPanel and Details are all missing **ClassName** methods: **Add**, **Set**, **Get**, **Has** and **Remove**.

Methods related to **ThemeName** seem to be available for AccordionPanel and Details.

**Comment by tomivirkki** [comment]
Needs also the `HasStyle` interface to the components (Accordion, Details)
