### ISSUE TITLE
CRUD does not react to AbstractCompositeField

### ISSUE THREAD

**Issue by fgrazi** [vaadin/vaadin-flow-components#565]
CRUD does not react to AbstractCompositeField

If you use a field derived from AbstractCompositeField CRUD does not recognizes changes.

Please try the attached custom field derived from AbstractCompositeField. This is not what I need (I need an upload field and I developed it but it does not work, same problem as attached field) but this is a minimal case to reproduce the bug. You can try this field inside the Bakery app, for example with the Product. First add a transient field (to avoid touching the DB) to the product:

```

Class Product {


  @Transient
  private Integer count;

  // Getters & Setters - I use Lombok but makes no diff.
  
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

}

```

Also import CounterField.java somewhere in your project. This is simply a horizontal layout with a button that increments an integer (attached).

Finally you can add a CounterField to ProductView:

```

  private static BinderCrudEditor<Product> createForm() {
  
      ...
	  CounterField cf = new CounterField(3);  // create with init value of 3
	  FormLayout form = new FormLayout(name, price, cf); // add to the form
	  ...
	  
	  binder.bind(cf, "count"); // bind it
	  ...
	  
	  // This is to be sure that the change is fired! log it if you prefer.
      binder.addValueChangeListener(new HasValue.ValueChangeListener<HasValue.ValueChangeEvent<?>>() {
        @Override
        public void valueChanged(HasValue.ValueChangeEvent<?> valueChangeEvent) {
          System.out.println("Change event: " + valueChangeEvent + " >-> " + binder.isValid());
        }
    });	  
	  
```

Now open a product, click the button one or more times and notice that the SAVE button does NOT get enabled (at least that is what I would expect - Am I wrong?)

If this is a bug and will take time to be fixed, can you please suggest a bypass so that I can go on with CRUD component, Otherwise I should go back and build one for me for V 14.
[CounterField.java.zip](https://github.com/vaadin/vaadin-flow-components/files/5815864/CounterField.java.zip)

**Comment by tulioag** [comment]
Hi @fgrazi 

Are you calling setDirty, like in this example?

https://github.com/vaadin/vaadin-flow-components/blob/5dd57360a6c7fce6e6f8bfb68e37d797136631c3/vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/main/java/com/vaadin/flow/component/crud/examples/CompositeView.java#L38

Also, are you setting the field value ?
https://github.com/vaadin/vaadin-flow-components/blob/5dd57360a6c7fce6e6f8bfb68e37d797136631c3/vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/main/java/com/vaadin/flow/component/crud/examples/CompositeView.java#L99

**Comment by fgrazi** [comment]
Hi Tulio,

Thanks for your reply. No, I did neither call set dirty nor set value from current value, and I can't understand why I should do that.
What I have submitted is a small example of a **reusable** field. Such field has no knowledge of where it is being used and consequently of any existence of a CRUD editor. And well, the value is set by the field itself as you can see by yourself when the increase button is pressed.

This field is actually useless, I coded it simply to report the issue. What does not work for me is a quite more complex field that uploads image to a Spring Content Store. The anomaly is the same but I could not report a problem with a lot of code because it would take you a lot of time to reproduce.

With this small example, simply add a "int count" attribute to the Product class of Bakery app and add the corresponding field to ProductsView. You will notice that if you increment the count the save button is not enabled.

I also added the following code:

```
binder.addValueChangeListener(new HasValue.ValueChangeListener<HasValue.ValueChangeEvent<?>>() {
      @Override
      public void valueChanged (HasValue.ValueChangeEvent < ? > valueChangeEvent){
        System.out.println("Change event: " + valueChangeEvent + " >-> valid:" + binder.isValid() +
            " , changed: " + binder.hasChanges());
      }
    });
```

And I see this on console:

Change event: ComponentValueChangeEvent[source=net.cbsolution.everylunch.ui.components.CounterField@7c028792, value = 17, oldValue = 16] >-> valid:true , changed: true

This means that the binder has changes but the button is *not* enabled.

Now, how is it possible that the other field changes enable the button but the count does not? Maybe I' m goofing at something or missing something but I was unable to find from documentation what.

Your example is quite specific, it uses a field constructed inside the CRUD editor. This is not what I would expect from a generic
CRUD. 

Please let me know if I am wrong.

Best

**Comment by tulioag** [comment]
Hi @fgrazi

I can see 2 workarounds.

The first is to add a `crud.setDirty(true)` to your binder listener.
```java
        binder.addValueChangeListener(
            new HasValue.ValueChangeListener<HasValue.ValueChangeEvent<?>>() {
                @Override
                public void valueChanged(
                    HasValue.ValueChangeEvent<?> valueChangeEvent) {
                    crud.setDirty(true);
                    System.out.println(
                        "Change event: " + valueChangeEvent + " >-> " + binder
                            .isValid());
                }
            });
```
The second is to force a client side event when the value is changed. In this example, it could be when the button is clicked.
```java
     public CounterField(Integer defaultValue) {
   ...
       incrementButton.addClickListener(e -> {
            setValue(getValue() + 1);
            incrementButton.getElement().executeJs("this.dispatchEvent(new CustomEvent('change', {bubbles: true}));");
        });
```
I hope this helps.

Best

**Comment by fgrazi** [comment]
Hi Tulio,

Thank you very much indeed! I was about to give up with CRUD component and write my own.

 Workaround 2 is surely the better, otherwise client code should create a listener for each CRUD component that uses custom editors. Also notice (still in the Bakery example) that the editor is returned to CRUD by a static method, so the CRUD has no knowledge of the binder (nor the binder of the CRUD).

Workaround 2 works, despite introducing low level JS in any custom editor only to fix an inconsistency of CRUD component. This was in fact my intention opening this issue: if CRUD component is inconsistent, I would expect it to be fixed (sooner or later), specially because it seems to me that this is not an open source component and only Vaadin team can fix it.

Finally, abusing of your patience, one more question. Where do I find the documentation of the 'change' custom event, and similar events that can exist and I am not aware of?

Thank you,

franco

**Comment by tulioag** [comment]
In the webcomponents you can see which events are fired, like for instance https://github.com/vaadin/vaadin-text-field/blob/28f9bf5887527e66cdf9f763e59944e14b1ebece/src/vaadin-text-field.js#L68-L71

But this requirement of a change event by Crud is something that needs to be documented properly or changed, so I will create an issue specifically about that.

**Comment by fgrazi** [comment]
Thanks Tulio, my question about the events is about **which kind of events do consumers expect** more than which event each component produces. Let me explain: I now know that the CRUD component expects a 'change' event to enable the save button, cause you told me, and that's enough, neither need to change requirements. But how could I know that a change event would make the CRUD component (that is not open source correct?) enable the save button? So I suppose that there is a table of standard event types, their usages and resulting actions, like there is, say, for Swing events. I understand that now this document is possibly internal only and constantly updated but would be a good addition to Vaadin book.

**Comment by tulioag** [comment]
AFAIK there is not a list of events that you should emit. I reported this dependency of CRUD on that specific event at https://github.com/vaadin/vaadin-crud/issues/239.  In my opinion this is a bug and just setting the value of the field on the server-side should be enough to enable the save button. 

Most Vaadin fields emit only `change` events and Polymer style `[property]-changed` events, which are at least `value-changed` and `invalid-changed`. 

CRUD has a commercial license, but you can still see the source code at https://github.com/vaadin/vaadin-crud/

**Comment by tulioag** [comment]
Closing in favour of https://github.com/vaadin/vaadin-crud/issues/239
