### ISSUE TITLE
Text update doesn't work when component is manually attached 

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-flow-components#685]
This issue
https://github.com/vaadin/vaadin-notification/issues/117
has been incorrectly transferred to the wrong repository by the bot.

I cannot transfer it to the correct repo because I don't have permissions apparently.
So I just link it here.

**Comment by tomivirkki** [comment]
@denis-anisimov Please read the issue template https://github.com/vaadin/vaadin-flow-components/issues/new?assignees=&labels=&template=custom.md&title=

**Comment by web-padawan** [comment]
As mentioned in the [issue template](https://github.com/vaadin/vaadin-flow-components/blob/master/.github/ISSUE_TEMPLATE/custom.md), we use this tracker mainly for issues related to the monorepo automation.
All the component-specific issues were intentionally transferred to the web component repositories.

BTW, the original issue vaadin/vaadin-notification#117 was still in New issues, so I moved it to Triaged.
