### ISSUE TITLE
Prepare a tool for moving tickets and label them in monorepo

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-flow-components#88]
We need to have a label per component in the monorepo.
Use github API (if there is one) otherwise we need to do with the UI.

**Comment by ZheSun88** [comment]
Pushed the script to [branch here](https://github.com/vaadin/vaadin-flow-components/tree/transfer-ticket)

As this will just be a one time project, let us don't save it in files.

Run the script `node ./scripts/transferTicket.js <githubUserName>:<githubToken>` and this will generate a bash script file `transferTicket.sh` which can be used by the [TeamCity build](https://bender.vaadin.com/viewType.html?buildTypeId=TestingProject_IssueTransfer)

Run the build when the day comes
